# Data Cleaning

In [0]:
import numpy as np
import pandas as pd

In [0]:
new_df = pd.read_csv('raw.csv')

In [3]:
# na count before clean
new_df.isnull().sum()

age           1
sex           1
cp            1
trestbps     59
chol          8
fbs          83
restecg       2
thalach      55
exang        55
oldpeak      63
slope       120
ca          321
thal        221
num           1
dtype: int64

In [0]:
def data_cleaning():

# Read new dataset
    df = new_df

#age          		
    df['age'].fillna(df['age'].mean(), inplace=True)

#sex          
    df['sex'].fillna(df['sex'].max(), inplace=True)

#CP 
    df['cp'].fillna(df['cp'].mean(), inplace=True)

#trestbps     
    trestbps_ngtv = df['trestbps'] < 0
    df.loc[trestbps_ngtv, 'trestbps'] = np.nan
    df['trestbps'].fillna(df['trestbps'].mean(), inplace=True)

#chol
    chol_ngtv = df['chol'] < 0
    df.loc[chol_ngtv, 'chol'] = np.nan
    df['chol'].fillna(df['chol'].mean(), inplace=True)

#fbs
    fbs_ngtv = df['fbs'] < 0
    df.loc[fbs_ngtv, 'fbs'] = np.nan
    df['fbs'].fillna(df['fbs'].max(), inplace=True)

#restecg
    restecg_ngtv = df['restecg'] < 0
    df.loc[restecg_ngtv, 'restecg'] = np.nan
    df['restecg'].fillna(df['restecg'].max(), inplace=True)

#Thalach
    thalach_ngtv = df['thalach'] < 0
    df.loc[thalach_ngtv, 'thalach'] = np.nan
    df['thalach'].fillna(df['thalach'].mean(), inplace=True)

#Exang
    exang_ngtv = df['exang'] < 0
    df.loc[exang_ngtv, 'exang'] = np.nan
    df['exang'].fillna(df['exang'].mean(), inplace=True)

#OldPeak
    oldpeak_ngtv = df['oldpeak'] < 0
    df.loc[oldpeak_ngtv, 'oldpeak'] = np.nan
    df['oldpeak'].fillna(df['oldpeak'].mean(), inplace=True)

#Slope
    slope_ngtv = df['slope'] < 0
    df.loc[slope_ngtv, 'slope'] = np.nan
    df['slope'].fillna(df['slope'].mean(), inplace=True)

#Ca
    ca_ngtv = df['ca'] < 0
    df.loc[ca_ngtv, 'ca'] = np.nan
    ca_more9 = df['ca'] > 9
    df.loc[ca_more9, 'ca'] = np.nan
    df['ca'].fillna(df['ca'].mean(), inplace=True)

#Thal
    thal_ngtv = df['thal'] < 0
    df.loc[thal_ngtv, 'thal'] = np.nan
    df['thal'].fillna(df['thal'].mean(), inplace=True)


#Num 
    df['num'].fillna(df['num'].max(), inplace=True)


#output
    print("\n")
    print("<------------- Data Info ------------->")
    df.info()

    return df

In [5]:
df = data_cleaning()

<------------- Data Info ------------->
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       921 non-null    float64
 1   sex       921 non-null    float64
 2   cp        921 non-null    float64
 3   trestbps  921 non-null    float64
 4   chol      921 non-null    float64
 5   fbs       921 non-null    float64
 6   restecg   921 non-null    float64
 7   thalach   921 non-null    float64
 8   exang     921 non-null    float64
 9   oldpeak   921 non-null    float64
 10  slope     921 non-null    float64
 11  ca        921 non-null    float64
 12  thal      921 non-null    float64
 13  num       921 non-null    float64
dtypes: float64(14)
memory usage: 100.9 KB

In [6]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
num         0
dtype: int64

In [7]:
df.sample(10)

      age  sex   cp  trestbps  ...     slope        ca      thal  num
430  48.0  0.0  4.0     108.0  ...  1.000000  0.703226  5.087558  0.0
331  53.0  0.0  2.0     113.0  ...  1.770867  0.703226  5.087558  0.0
58   54.0  1.0  3.0     125.0  ...  3.000000  1.000000  3.000000  0.0
668  58.0  1.0  4.0     130.0  ...  2.000000  0.703226  6.000000  4.0
22   58.0  1.0  2.0     120.0  ...  2.000000  0.000000  3.000000  1.0
30   69.0  0.0  1.0     140.0  ...  1.000000  2.000000  3.000000  0.0
369  45.0  0.0  4.0     132.0  ...  1.770867  0.703226  5.087558  0.0
274  59.0  1.0  1.0     134.0  ...  1.000000  2.000000  3.000000  1.0
353  50.0  1.0  4.0     130.0  ...  2.000000  0.703226  7.000000  2.0
823  48.0  1.0  3.0     102.0  ...  3.000000  0.703226  5.087558  1.0

[10 rows x 14 columns]

End of Checkpoint 2